stages: [prepare, build, deploy]
variables:
    PROJECT_NAME: "erp-front"
build_all:
  stage: build
  script:
    - "echo starting"
include:
#  - 'cicd/accounts/deploy-stage.yml'
  - 'cicd/erp-front/erp.yml'
